FROM python:3.13.1-slim

WORKDIR /app

COPY README.md .
COPY pyproject.toml .
COPY src/ src/

RUN pip install --no-cache-dir -e .

CMD ["python", "-m", "src.order_book_simulator.market_data.db_consumer"]
