services:
  postgres:
    build:
      context: ..
      dockerfile: docker/Dockerfile.postgresql
    environment:
      - POSTGRES_DB=orderbook_db
      - POSTGRES_USER=orderbook_user
      - POSTGRES_PASSWORD=orderbook_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:29093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: "order-book-dev-cluster-01"
    healthcheck:
      test: nc -z localhost 9092 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data

  gateway:
    build:
      context: ..
      dockerfile: docker/Dockerfile.gateway
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://orderbook_user:orderbook_password@postgres:5432/orderbook_db
    ports:
      - "8000:8000"

  matching:
    build:
      context: ..
      dockerfile: docker/Dockerfile.matching
    depends_on:
      - kafka

  market-data:
    build:
      context: ..
      dockerfile: docker/Dockerfile.market_data
    depends_on:
      - kafka

volumes:
  kafka_data:
    driver: local
  postgres_data:
    driver: local
