FROM python:3.13-slim

WORKDIR /app

COPY pyproject.toml uv.lock README.md ./
COPY src/ ./src/

RUN pip install uv && uv sync --frozen

CMD ["uv", "run", "python", "-m", "order_book_simulator.market_data.db_consumer"]
