FROM python:3.14-slim

WORKDIR /app

COPY pyproject.toml uv.lock README.md ./
COPY src/ ./src/
COPY resources/ ./resources/

RUN apt-get update && apt-get install -y netcat-traditional && rm -rf /var/lib/apt/lists/*
RUN pip install uv && uv sync --frozen

CMD ["uv", "run", "uvicorn", "order_book_simulator.gateway.app:app", "--host", "0.0.0.0", "--port", "8000"]
