FROM python:3.14-slim

WORKDIR /app

COPY pyproject.toml uv.lock README.md ./
COPY src/ ./src/

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libc-dev \
    zlib1g-dev \
    && pip install uv && uv sync --frozen \
    && apt-get purge -y gcc libc-dev zlib1g-dev \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*

CMD ["uv", "run", "python", "-m", "order_book_simulator.matching.order_consumer"]
