FROM python:3.13.1-slim

WORKDIR /app

COPY README.md .
COPY pyproject.toml .
COPY src/ src/

RUN pip install --no-cache-dir -e .

CMD ["uvicorn", "src.order_book_simulator.gateway.app:app", "--host", "0.0.0.0", "--port", "8000"]
